--- #YAML:1.0
name: Net-RTP
version: 0.05
author:
  - Nicholas J Humfrey, njh@cpan.org
abstract: Send and receive RTP packets (RFC3550)
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
