---
name: Net-RTP
version: 0.02
author:
  - 'Nicholas Humfrey, njh@cpan.org'
abstract: Send and recieve RTP packets (RFC3550)
license: gpl
requires:
  IO::Socket::Multicast: 1.04
  Test: 1.00
build_requires:
  Module::Build: 0.20
provides:
  Net::RTP:
    file: lib/Net/RTP.pm
    version: 0.02
  Net::RTP::Packet:
    file: lib/Net/RTP/Packet.pm
    version: 0.02
generated_by: Module::Build version 0.2611
